local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 7.0
  height: 7.0
  resolution: 0.08
  plugins:
     - {name: obstacles_costmap2d,       type: "costmap_2d::ObstacleLayer"}
     - {name: inflation,                 type: "costmap_2d::InflationLayer"}
